-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 11:25:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `idUSUARIO` INT NOT NULL,
  `Nombre_Usuario` VARCHAR(20) NULL,
  `Apellidos_Usuario` VARCHAR(75) NULL,
  `Fecha_Nacimiento` DATE NULL,
  `ROL` VARCHAR(15) NULL,
  PRIMARY KEY (`idUSUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SERVIDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SERVIDOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SERVIDOR` (
  `idSERVIDOR` INT NOT NULL,
  `NombreServidor` VARCHAR(45) NULL,
  `Descripción` VARCHAR(75) NULL,
  `SERVIDORcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idSERVIDOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERMISO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PERMISO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PERMISO` (
  `Num_Permiso` INT NOT NULL,
  `Función` VARCHAR(75) NULL,
  `Nombre` VARCHAR(15) NULL,
  PRIMARY KEY (`Num_Permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ROL` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ROL` (
  `Nombre_Rol` INT NOT NULL,
  `Descripción` VARCHAR(45) NULL,
  `USUARIO_idUSUARIO` INT NOT NULL,
  `PERMISO_Num_Permiso` INT NOT NULL,
  INDEX `fk_ROL_USUARIO_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  INDEX `fk_ROL_PERMISO1_idx` (`PERMISO_Num_Permiso` ASC) VISIBLE,
  CONSTRAINT `fk_ROL_USUARIO`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROL_PERMISO1`
    FOREIGN KEY (`PERMISO_Num_Permiso`)
    REFERENCES `mydb`.`PERMISO` (`Num_Permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entra/Crea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entra/Crea` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entra/Crea` (
  `USUARIO_idUSUARIO` INT NOT NULL,
  `SERVIDOR_idSERVIDOR` INT NOT NULL,
  `fecha_entrada/creación` DATE NULL,
  PRIMARY KEY (`USUARIO_idUSUARIO`, `SERVIDOR_idSERVIDOR`),
  INDEX `fk_USUARIO_has_SERVIDOR_SERVIDOR1_idx` (`SERVIDOR_idSERVIDOR` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_SERVIDOR_USUARIO1_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_SERVIDOR_USUARIO1`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_SERVIDOR_SERVIDOR1`
    FOREIGN KEY (`SERVIDOR_idSERVIDOR`)
    REFERENCES `mydb`.`SERVIDOR` (`idSERVIDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MENSAJE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MENSAJE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MENSAJE` (
  `idMENSAJE` INT NOT NULL,
  `Longitud_Caracteres` VARCHAR(45) NULL,
  `Tamaño_Archivos` VARCHAR(45) NULL,
  `Fecha_Envío` VARCHAR(45) NULL,
  `USUARIO_idUSUARIO` INT NOT NULL,
  `SERVIDOR_idSERVIDOR` INT NOT NULL,
  PRIMARY KEY (`idMENSAJE`),
  INDEX `fk_MENSAJE_USUARIO1_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  INDEX `fk_MENSAJE_SERVIDOR1_idx` (`SERVIDOR_idSERVIDOR` ASC) VISIBLE,
  CONSTRAINT `fk_MENSAJE_USUARIO1`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MENSAJE_SERVIDOR1`
    FOREIGN KEY (`SERVIDOR_idSERVIDOR`)
    REFERENCES `mydb`.`SERVIDOR` (`idSERVIDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LLAMADA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LLAMADA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LLAMADA` (
  `idLLAMADA` INT NOT NULL,
  `Fecha_Inicio` DATETIME NULL,
  `Fecha_Fin` DATETIME NULL,
  `USUARIO_idUSUARIO` INT NOT NULL,
  PRIMARY KEY (`idLLAMADA`),
  INDEX `fk_LLAMADA_USUARIO1_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_LLAMADA_USUARIO1`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entra` (
  `LLAMADA_idLLAMADA` INT NOT NULL,
  `USUARIO_idUSUARIO` INT NOT NULL,
  `hora_entrada` DATETIME NULL,
  `hora_salida` DATETIME NULL,
  PRIMARY KEY (`LLAMADA_idLLAMADA`, `USUARIO_idUSUARIO`),
  INDEX `fk_LLAMADA_has_USUARIO_USUARIO1_idx` (`USUARIO_idUSUARIO` ASC) VISIBLE,
  INDEX `fk_LLAMADA_has_USUARIO_LLAMADA1_idx` (`LLAMADA_idLLAMADA` ASC) VISIBLE,
  CONSTRAINT `fk_LLAMADA_has_USUARIO_LLAMADA1`
    FOREIGN KEY (`LLAMADA_idLLAMADA`)
    REFERENCES `mydb`.`LLAMADA` (`idLLAMADA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LLAMADA_has_USUARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUSUARIO`)
    REFERENCES `mydb`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
